"""Add: is_plagiat column in comparison

Revision ID: 07537a054b5d
Revises: bf8c96536cee
Create Date: 2026-06-09 15:36:03.642203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07537a054b5d'
down_revision: Union[str, Sequence[str], None] = 'bf8c96536cee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comparisons', sa.Column('is_plagiat', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comparisons', 'is_plagiat')
    # ### end Alembic commands ###
