"""revision mapping_preprocess column

Revision ID: 2f7b8484f816
Revises: 14405a87e90c
Create Date: 2026-04-21 21:30:27.928904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f7b8484f816'
down_revision: Union[str, Sequence[str], None] = '14405a87e90c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mappings', sa.Column('mapping_preprocess', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('mappings', 'mapping_tpreproccess')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mappings', sa.Column('mapping_tpreproccess', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('mappings', 'mapping_preprocess')
    # ### end Alembic commands ###
