"""create jobs

Revision ID: 30f8c8b0a069
Revises: dae0f8966919
Create Date: 2026-04-18 14:40:28.176559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30f8c8b0a069'
down_revision: Union[str, Sequence[str], None] = 'dae0f8966919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'COMPLETED')", name='check_job_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.add_column('documents', sa.Column('path', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('job_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_documents_job_id'), 'documents', ['job_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_job_id'), table_name='documents')
    op.drop_column('documents', 'job_id')
    op.drop_column('documents', 'path')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
