"""create block embedding table

Revision ID: 490d878c0ec0
Revises: 07537a054b5d
Create Date: 2026-06-10 14:57:43.057096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '490d878c0ec0'
down_revision: Union[str, Sequence[str], None] = '07537a054b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.REAL()), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_embeddings_block_id'), 'block_embeddings', ['block_id'], unique=True)
    op.create_index(op.f('ix_block_embeddings_id'), 'block_embeddings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_block_embeddings_id'), table_name='block_embeddings')
    op.drop_index(op.f('ix_block_embeddings_block_id'), table_name='block_embeddings')
    op.drop_table('block_embeddings')
    # ### end Alembic commands ###
