"""Add column mapping

Revision ID: 95ce2d4c50cd
Revises: 490d878c0ec0
Create Date: 2026-06-14 13:54:19.875748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95ce2d4c50cd'
down_revision: Union[str, Sequence[str], None] = '490d878c0ec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mappings', sa.Column('mapping_hash', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('mappings', 'is_detect')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mappings', sa.Column('is_detect', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('mappings', 'mapping_hash')
    # ### end Alembic commands ###
