"""init uuid schema

Revision ID: 9615359aa2ce
Revises: 
Create Date: 2026-04-17 15:08:30.088402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9615359aa2ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("source IN ('TYPING', 'IMAGE')", name='check_block_source'),
    sa.CheckConstraint("type IN ('TEXT', 'CODE', 'TERMINAL')", name='check_block_type'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocks_document_id'), 'blocks', ['document_id'], unique=False)
    op.create_index(op.f('ix_blocks_id'), 'blocks', ['id'], unique=False)
    op.create_table('comparisons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text_score', sa.Float(), nullable=True),
    sa.Column('code_score', sa.Float(), nullable=True),
    sa.Column('phrase_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('document_1_id', sa.UUID(), nullable=False),
    sa.Column('document_2_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('document_1_id != document_2_id', name='no_self_comparison'),
    sa.ForeignKeyConstraint(['document_1_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_2_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comparison_docs', 'comparisons', ['document_1_id', 'document_2_id'], unique=False)
    op.create_index(op.f('ix_comparisons_document_1_id'), 'comparisons', ['document_1_id'], unique=False)
    op.create_index(op.f('ix_comparisons_document_2_id'), 'comparisons', ['document_2_id'], unique=False)
    op.create_index(op.f('ix_comparisons_id'), 'comparisons', ['id'], unique=False)
    op.create_table('hashes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fingerprint', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("type IN ('TEXT', 'CODE')", name='check_hash_type'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hashes_document_id'), 'hashes', ['document_id'], unique=False)
    op.create_index(op.f('ix_hashes_id'), 'hashes', ['id'], unique=False)
    op.create_table('mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mapping_doc', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mapping_text_code', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mapping_tpreproccess', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_detect', sa.Boolean(), nullable=True),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mappings_block_id'), 'mappings', ['block_id'], unique=True)
    op.create_index(op.f('ix_mappings_id'), 'mappings', ['id'], unique=False)
    op.create_table('rkrgsts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('position_1_start', sa.Integer(), nullable=True),
    sa.Column('position_2_start', sa.Integer(), nullable=True),
    sa.Column('match_length', sa.Integer(), nullable=True),
    sa.Column('comparison_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("type IN ('TEXT', 'CODE')", name='check_rkrgst_type'),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparisons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rkrgsts_comparison_id'), 'rkrgsts', ['comparison_id'], unique=False)
    op.create_index(op.f('ix_rkrgsts_id'), 'rkrgsts', ['id'], unique=False)
    op.create_table('sberts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('block_1_id', sa.UUID(), nullable=False),
    sa.Column('block_2_id', sa.UUID(), nullable=False),
    sa.Column('comparison_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['block_1_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['block_2_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparisons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sbert_blocks', 'sberts', ['block_1_id', 'block_2_id'], unique=False)
    op.create_index(op.f('ix_sberts_block_1_id'), 'sberts', ['block_1_id'], unique=False)
    op.create_index(op.f('ix_sberts_block_2_id'), 'sberts', ['block_2_id'], unique=False)
    op.create_index(op.f('ix_sberts_comparison_id'), 'sberts', ['comparison_id'], unique=False)
    op.create_index(op.f('ix_sberts_id'), 'sberts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sberts_id'), table_name='sberts')
    op.drop_index(op.f('ix_sberts_comparison_id'), table_name='sberts')
    op.drop_index(op.f('ix_sberts_block_2_id'), table_name='sberts')
    op.drop_index(op.f('ix_sberts_block_1_id'), table_name='sberts')
    op.drop_index('idx_sbert_blocks', table_name='sberts')
    op.drop_table('sberts')
    op.drop_index(op.f('ix_rkrgsts_id'), table_name='rkrgsts')
    op.drop_index(op.f('ix_rkrgsts_comparison_id'), table_name='rkrgsts')
    op.drop_table('rkrgsts')
    op.drop_index(op.f('ix_mappings_id'), table_name='mappings')
    op.drop_index(op.f('ix_mappings_block_id'), table_name='mappings')
    op.drop_table('mappings')
    op.drop_index(op.f('ix_hashes_id'), table_name='hashes')
    op.drop_index(op.f('ix_hashes_document_id'), table_name='hashes')
    op.drop_table('hashes')
    op.drop_index(op.f('ix_comparisons_id'), table_name='comparisons')
    op.drop_index(op.f('ix_comparisons_document_2_id'), table_name='comparisons')
    op.drop_index(op.f('ix_comparisons_document_1_id'), table_name='comparisons')
    op.drop_index('idx_comparison_docs', table_name='comparisons')
    op.drop_table('comparisons')
    op.drop_index(op.f('ix_blocks_id'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_document_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
