"""Add: column sequence in block table

Revision ID: bf8c96536cee
Revises: fc2c60579ba1
Create Date: 2026-06-06 12:22:13.369205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf8c96536cee'
down_revision: Union[str, Sequence[str], None] = 'fc2c60579ba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('sequence', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blocks', 'sequence')
    # ### end Alembic commands ###
