"""delete order column in blocks table

Revision ID: dae0f8966919
Revises: 9615359aa2ce
Create Date: 2026-04-17 15:12:24.556538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae0f8966919'
down_revision: Union[str, Sequence[str], None] = '9615359aa2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blocks', 'order')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
