"""Edit Job Model

Revision ID: e4ac03b26b8b
Revises: 66eee606cc3f
Create Date: 2026-05-21 13:07:14.833728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ac03b26b8b'
down_revision: Union[str, Sequence[str], None] = '66eee606cc3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('scenario', sa.String(length=10), nullable=True))
    op.add_column('jobs', sa.Column('treshold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'treshold')
    op.drop_column('jobs', 'scenario')
    op.drop_column('jobs', 'description')
    # ### end Alembic commands ###
