"""Add job status & weight column

Revision ID: fc2c60579ba1
Revises: bc0b1c296346
Create Date: 2026-06-03 13:32:35.182769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc2c60579ba1'
down_revision: Union[str, Sequence[str], None] = 'bc0b1c296346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('threshold', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column('weight_text', sa.Float(), nullable=False))
    op.add_column('jobs', sa.Column('weight_code', sa.Float(), nullable=False))
    op.add_column('jobs', sa.Column('weight_phrase', sa.Float(), nullable=False))
    op.drop_column('jobs', 'treshold')
    # ### end Alembic commands ###
    
    op.create_check_constraint(
        "check_job_scenario",
        "jobs",
        "scenario IN ('SINGLE', 'MULTIPLE')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('treshold', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'weight_phrase')
    op.drop_column('jobs', 'weight_code')
    op.drop_column('jobs', 'weight_text')
    op.drop_column('jobs', 'threshold')
    # ### end Alembic commands ###

    op.drop_constraint(
        "check_job_scenario",
        "jobs",
        type_="check"
    )
